[[pages]]
path = "main.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "pages/topic_modelling.py"
name = "Topic Modelling"
icon = "ðŸ“–"

[[pages]]
path = "pages/topic_trajectory.py"
name = "Topic Trajectory"
icon = "ðŸš€"

[[pages]]
path = "pages/network.py"
name = "Network"
icon = "ðŸ“¡"

[[pages]]
path = "pages/simulations.py"
name = "Simulations"
icon = "ðŸŽ¡"

[[pages]]
path = "pages/interact.py"
name = "QA"
icon = "ØŸ"
